#!/bin/sh
day="$1"
part="$2"
inputfile="$3"

# create run
if [ -f "${day}.hs" ]; then
	stack build
	stack ghc -- -O3 "${day}.hs" -o run
else
	cp "${day}-${part}.sh" run

	# compile map if needed
	if grep -F -q ./map run; then
		stack build
		stack ghc -- -O3 map.hs
	fi
fi
